#!/usr/bin/env bash

# first argument is the name of the subproject
subproject_name=$1
# build
echo "building $subproject_name ..."
./build $subproject_name
if [ $? -ne 0 ]; then
    echo "build failed" >&2
    exit 1
fi
echo "build ok"
# run
echo "running $subproject_name ..."
./run $subproject_name
if [ $? -ne 0 ]; then
    exit 1
fi
